[tool.mypy]
python_version = "3.10"
warn_return_any = true
ignore_missing_imports = true

disable_error_code = [
    # Allow redefinitions since we redefine an error variable before raising exceptions
    "no-redef"
]

exclude = [
    '^umu_test\.py$',
    '^umu_test_plugins\.py$',
]
